#!/bin/bash
latticeDims="(11,11)"
characteristicNames=$1
analysisRegion=$2
python analyzeCellularFieldNetwork.py --latticeDims $latticeDims --fieldEnabled $fieldEnabled --fieldResolution $fieldResolution --fieldAggregation $fieldAggregation --fieldScreenSize $fieldScreenSize --fieldStrengthProp $fieldStrengthProp --ligandEnabled $ligandEnabled --GJStrength $GJStrength --randomizeInitialStates $randomizeInitialStates --characteristicNames $characteristicNames --numSamples $numSamples --numSimIters $numSimIters --numPerturbSimIters $numPerturbSimIters --perturbationMode $perturbationMode --analysisMode $analysisMode --analysisRegion $analysisRegion --numGradientTimePoints $numGradientTimePoints --fileNumber $SLURM_ARRAY_TASK_ID --fileNumberVersion $fileNumberVersion --verbose $verbose
#sbatch --export=ALL,analysisMode=fixBiasSweepWeightScreenGJ,fieldResolution=1,fieldAggregation=average,fieldScreenSize=0,fieldStrengthProp=1.0,GJStrength=0.05,randomizeInitialStates=False,numSamples=1,perturbationMode=None,analysisRegion=representative,numSimIters=500,numPerturbSimIters=0,numGradientTimePoints=25,fileNumberVersion=0,verbose=False --time 2-0:00:00 -p batch --array 1-500 -e Error_%A_%a.err --mem 40G runAnalyzeCellularFieldNetwork.sh "['Hessian']"
#sbatch --export=ALL,analysisMode=fixBiasSweepWeightLigandGJ,fieldEnabled=False,fieldResolution=1,fieldAggregation=average,fieldScreenSize=0,fieldStrengthProp=0.0,ligandEnabled=True,GJStrength=0.05,randomizeInitialStates=False,numSamples=1,perturbationMode=None,analysisRegion=representative,numSimIters=500,numPerturbSimIters=0,numGradientTimePoints=25,fileNumberVersion=0,verbose=False --time 2-0:00:00 -p batch --array 1-500 -e Error_%A_%a.err --mem 40G runAnalyzeCellularFieldNetwork.sh "['Hessian']"
#sbatch --export=ALL,analysisMode=fixBiasSweepWeightScreenGJ,fieldEnabled=True,fieldResolution=1,fieldAggregation=average,fieldScreenSize=0,fieldStrengthProp=1.0,GJStrength=0.05,randomizeInitialStates=True,numSamples=101,perturbationMode=None,analysisRegion=full,numSimIters=1000,numPerturbSimIters=0,numGradientTimePoints=0,fileNumberVersion=0,verbose=False --time 2-0:00:00 -p batch --array 1-500 -e Error_%A_%a.err --mem 10G runAnalyzeCellularFieldNetwork.sh "['Covariance']"
#sbatch --export=ALL,analysisMode=fixBiasSweepWeightScreenGJ,fieldEnabled=True,fieldResolution=1,fieldAggregation=average,fieldScreenSize=0,fieldStrengthProp=1.0,ligandEnabled=False,GJStrength=0.05,randomizeInitialStates=True,numSamples=101,perturbationMode=None,analysisRegion=full,numSimIters=5000,numPerturbSimIters=0,numGradientTimePoints=0,fileNumberVersion=0,verbose=False --time 2-0:00:00 -p batch --array 1-500 -e Error_%A_%a.err --mem 10G runAnalyzeCellularFieldNetwork.sh "['Covariance']"
#sbatch --export=ALL,analysisMode=fixBiasSweepWeightLigandGJ,fieldEnabled=False,fieldResolution=1,fieldAggregation=average,fieldScreenSize=0,fieldStrengthProp=0.0,ligandEnabled=True,GJStrength=0.05,randomizeInitialStates=False,numSamples=1,perturbationMode=None,numSimIters=500,numPerturbSimIters=0,numGradientTimePoints=100,fileNumberVersion=0,SLURM_ARRAY_TASK_ID=1939,verbose=False --time 4-0:00:00 -p batch --mem 40G runAnalyzeCellularFieldNetwork.sh "None" "[29,30,40,41]"