#!/bin/bash
latticeDims="(11,11)"
#fieldResolution=4
#fieldAggregation="average"
#fieldScreenSize=4
#GJStrength=0.05
#clampMode="tissueLigand"
#clampType="staticRandom"
#clampedCellsProp=1.0
#clampDurationProp=0.1
clampAmplitudeRange=$1
vmemToLigandCurrentStrengthRange=$2
learnedParameters=$3
clampFrequencyRange="(100.0,1000.0)"
numSamples=1
#numSimIters=100
#numLearnIters=100
#SLURM_ARRAY_TASK_ID=0
#verbose="True"
#learnedParameters1="['fieldTransductionWeight','fieldTransductionBias','clampFrequencies','clampPhases']"
#learnedParameters2="['ligandGatingWeight','ligandGatingBias','ligandCurrentStrength','clampFrequencies','clampPhases']"
#learnedParameters3="['ligandGatingWeight','ligandGatingBias','ligandCurrentStrength','clampValuesStatic']"
#python learnCellularFieldNetwork.py --latticeDims $latticeDims --fieldResolution $fieldResolution --fieldAggregation $fieldAggregation --fieldScreenSize $fieldScreenSize --GJStrength $GJStrength --clampMode $clampMode --clampType $clampType --clampedCellsProp $clampedCellsProp --clampDurationProp $clampDurationProp --clampAmplitudeRange $clampAmplitudeRange --clampFrequencyRange $clampFrequencyRange --numClampCoreSquares $numClampCoreSquares --numSamples $numSamples --numSimIters $numSimIters --numLearnIters $numLearnIters --learnedParameters $learnedParameters --fileNumber $SLURM_ARRAY_TASK_ID --verbose $verbose
python learnCellularFieldNetwork.py --latticeDims $latticeDims --fieldEnabled $fieldEnabled --fieldScreenSize $fieldScreenSize --fieldStrength $fieldStrength --fieldTransductionWeight $fieldTransductionWeight --fieldTransductionGain $fieldTransductionGain --fieldRangeSymmetric $fieldRangeSymmetric --fieldVector $fieldVector --ligandEnabled $ligandEnabled --vmemToLigandCurrentStrengthRange $vmemToLigandCurrentStrengthRange --GJStrength $GJStrength --clampMode $clampMode --clampType $clampType --clampedCellsProp $clampedCellsProp --clampDurationProp $clampDurationProp --clampAmplitudeRange $clampAmplitudeRange --clampFrequencyRange $clampFrequencyRange --numSamples $numSamples --numSimIters $numSimIters --numLearnIters $numLearnIters --numLearnTrials $numLearnTrials --evalDurationProp $evalDurationProp --learnedParameters $learnedParameters --parameterGridSweep $parameterGridSweep --lossMethod $lossMethod --lr $lr --fileNumber $SLURM_ARRAY_TASK_ID --verbose $verbose
#python learnCellularFieldNetwork.py --latticeDims $latticeDims --fieldResolution $fieldResolution --fieldAggregation $fieldAggregation --fieldScreenSize $fieldScreenSize --clampMode $clampMode --clampType $clampType --clampedCellsProp $clampedCellsProp --clampDurationProp $clampDurationProp --clampAmplitudeRange $clampAmplitudeRange --clampFrequencyRange $clampFrequencyRange --numClampCoreSquares $numClampCoreSquares --numSamples $numSamples --numSimIters $numSimIters --numLearnIters $numLearnIters --learnedParameters $learnedParameters --fileNumber $SLURM_ARRAY_TASK_ID --verbose $verbose
#sbatch --export=ALL --time 2-00:00:00 -p batch --array 1-100 -e Error_%A_%a.err --mem 12G runLearnCellularFieldNetwork.sh
#sbatch --export=ALL --time 2-00:00:00 -p batch --array 101-200 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh
#sbatch --export=ALL,fieldResolution=4,fieldAggregation=sum,clampMode=fieldDome,clampType=oscillatory,verbose=True --time 2-00:00:00 -p batch --array 401-500 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh
#sbatch --export=ALL,fieldResolution=1,fieldAggregation=average,fieldScreenSize=1,GJStrength=1.0,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,verbose=False --time 2-00:00:00 -p batch --array 1701-1800 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh
#sbatch --export=ALL,fieldEnabled=False,fieldScreenSize=0,ligandEnabled=True,GJStrength=0.05,clampMode=tissueDomeLigandTwoFoldSymmetry,clampType=staticRandom,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 301-400 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh
#learnedParameters1="['fieldTransductionWeight','fieldTransductionBias','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=21,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 901-1000 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-10.0,10.0)" "['fieldTransductionWeight','fieldTransductionBias','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=1,fieldStrength=10.0,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 701-800 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-100.0,100.0)" "(0.0,0.0)" "['fieldTransductionWeight','fieldTransductionBias','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=4,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=2000,numLearnIters=50000,evalDurationProp=0.5,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 1001-1100 -e Error_%A_%a.err --mem 10G runLearnCellularFieldNetwork.sh "(-100.0,100.0)" "None" "['fieldTransductionWeight','fieldTransductionBias','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=False,fieldScreenSize=0,fieldStrength=0.0,ligandEnabled=True,GJStrength=0.05,clampMode=tissueLigand,clampType=staticRandom,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 301-400 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(0.0,1.0)" "(0.1,10.0)" "['ligandGatingWeight','ligandGatingBias','ligandCurrentStrength','vmemToLigandCurrentStrength','clampValuesStatic']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=1,fieldStrength=10.0,ligandEnabled=True,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 1801-1900 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-100.0,100.0)" "(0.1,10.0)" "['fieldTransductionWeight','fieldTransductionBias','ligandGatingWeight','ligandGatingBias','ligandCurrentStrength','vmemToLigandCurrentStrength','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=1,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=500,numLearnIters=5000,numLearnTrials=100,evalDurationProp=0.1,parameterGridSweep=fixBiasSweepWeightScreenGJ,lossMethod=globalsum,verbose=False --time 4-00:00:00 -p batch --array 1-500 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-100.0,100.0)" "None" "['clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=1,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=500,numLearnIters=5000,numLearnTrials=100,evalDurationProp=0.1,parameterGridSweep=fixBiasSweepWeightScreenGJ,lossMethod=globalsum,verbose=False --time 4-00:00:00 -p batch --array=3,4,15,16,19,22,23,24,27,34,35,36,39,46,48,49,50,52,54,57,59,62,65,68,69,70,73,77,80,82,84,85,86,90,93,94,95,96,97,102,114,129,132,135,144,146,147,149,152,154,155,156,158,160,162,163,168,170,174,175,176,180,183,184,186,187,188,189,192,193,194,195,196,197,199,200,203,204,220,247,263,282,285,292,346,348,358,359,362,364,367,376,379,387,393,399,425,453,464,478,500 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-100.0,100.0)" "None" "['clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=1,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeLeftHalf,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=10000,numLearnTrials=1,evalDurationProp=0.1,parameterGridSweep=None,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 1901-1980 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-100.0,100.0)" "None" "['fieldTransductionWeight','fieldTransductionBias','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=4,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,numLearnTrials=1,evalDurationProp=0.1,parameterGridSweep=None,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 401-500 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-1000.0,1000.0)" "None" "['fieldTransductionWeight','fieldTransductionBias','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=1,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,numLearnTrials=1,evalDurationProp=0.1,parameterGridSweep=None,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 701-800 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-1000.0,1000.0)" "None" "['fieldTransductionWeight','fieldTransductionBias','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=21,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,numLearnTrials=1,evalDurationProp=0.1,parameterGridSweep=None,lossMethod=globalsum,verbose=False --time 2-00:00:00 -p batch --array 801-900 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-1000.0,1000.0)" "None" "['fieldTransductionWeight','fieldTransductionBias','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=0,fieldRangeSymmetric=False,fieldTransductionGain=10,ligandEnabled=False,GJStrength=0.0,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=500,numLearnIters=5000,numLearnTrials=100,evalDurationProp=0.1,parameterGridSweep=fixBiasSweepWeightScreenGJ,lossMethod=globalsum,verbose=False --time 4-00:00:00 -p batch --array 1-500 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-100.0,100.0)" "None" "['clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=21,fieldRangeSymmetric=False,fieldTransductionGain=1,fieldVector=True,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,numLearnTrials=1,evalDurationProp=0.1,parameterGridSweep=None,lossMethod=globalsum,lr=0.01,verbose=False --time 5-00:00:00 -p batch --array 801-900 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-1.0,1.0)" "None" "['fieldTransductionBias','clampFrequencies','clampPhases']"
#sbatch --export=ALL,fieldEnabled=True,fieldScreenSize=4,fieldStrength=10,fieldTransductionWeight=10,fieldTransductionGain=1000,fieldRangeSymmetric=False,fieldVector=True,ligandEnabled=False,GJStrength=0.05,clampMode=fieldDomeTwoFoldSymmetry,clampType=oscillatory,clampedCellsProp=1.0,clampDurationProp=0.1,numSimIters=1000,numLearnIters=50000,numLearnTrials=1,evalDurationProp=0.1,parameterGridSweep=None,lossMethod=globalsum,lr=0.01,verbose=False --time 5-00:00:00 -p batch --array 401-500 -e Error_%A_%a.err --mem 4G runLearnCellularFieldNetwork.sh "(-1.0,1.0)" "None" "['fieldTransductionBias','clampFrequencies','clampPhases']"


