#!/bin/bash
dims=$1
python simulateEmbryoNetwork.py --dims $dims --teratogenExposure $teratogenExposure --boundaryAssistance $boundaryAssistance --GRNEnabled $GRNEnabled --LigandEnabled $LigandEnabled --modelNameEmbryo $modelNameEmbryo --modelNameATP $modelNameATP --nsamples $nsamples --niters $niters --sampleNumber $SLURM_ARRAY_TASK_ID --save $save
#sbatch --export=ALL,teratogenExposure=True,modelNumEmbryo=253,modelNumATP=262,save=True --time 2-00:00:00 -p batch --mem 4G runSimulateEmbryoNetwork.sh "(10,10)"
#sbatch --export=ALL,teratogenExposure=True,modelNumEmbryo=253,modelNumATP=262,save=True --time 2-00:00:00 -p batch --mem 10G runSimulateEmbryoNetwork.sh "(15,15)"
#sbatch --export=ALL,teratogenExposure=True,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(10,10)"
#sbatch --export=ALL,teratogenExposure=True,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(15,15)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=False,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(10,10)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=False,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(15,15)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=False,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-100 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(5,5)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=False,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(20,20)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=True,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(20,20)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=True,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(15,15)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=True,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(10,10)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=True,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(5,5)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=True,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(3,3)"
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=True,modelNumEmbryo=253,modelNumATP=262,nsamples=1,niters=2000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(1,1)"
## Updated model
#sbatch --export=ALL,teratogenExposure=True,boundaryAssistance=False,GRNEnabled=False,LigandEnabled=False,modelNameEmbryo=Stigmergic,modelNameATP=262,nsamples=1,niters=1000,save=True --time 2-00:00:00 -p batch --array 1-200 -e Error_%A_%a.err --mem 4G runSimulateEmbryoNetwork.sh "(15,15)"