
(function relayLoopStripes(){
  const RL=D.relayLoop, LAB=D.steering;
  if(!RL||!LAB) return;
  ['rlTitle','relayLoopStripes'].forEach(id=>{ document.getElementById(id).style.display=''; });
  const M=80, CM=42;         // margin and cell size, matching the movie's own grid; the grid itself is 11 cells, M to M+11*CM
  const P=(cx,cy)=>({x:M+cx*CM, y:M+cy*CM});
  // dir: which way the label points, outward from the grid; lines: what it says, one string per line
  const NODES={
    ringTop:   {lines:['ring top'],    dir:'above', cat:'ring',    ...P(5.5,0.5)},
    ringBottom:{lines:['ring bottom'], dir:'below', cat:'ring',    ...P(5.5,10.5)},
    ringLeft:  {lines:['ring left'],   dir:'left',  cat:'ring',    ...P(0.5,5.5)},
    ringRight: {lines:['ring right'],  dir:'right', cat:'ring',    ...P(10.5,5.5)},
    stripeUpper:{lines:['stripe','upper'], dir:'right', cat:'feature', ...P(5.5,3.39)},   /* the centre of mass of rows 1-4 and half of row 5, as the relay's blocks cut it */
    stripeLower:{lines:['stripe','lower'], dir:'right', cat:'feature', ...P(5.5,7.61)},
    flankLeftUpper: {lines:['left flank','upper'],  dir:'left',  cat:'quad', ...P(2.5,3.39)},
    flankRightUpper:{lines:['right flank','upper'], dir:'right', cat:'quad', ...P(8.5,3.39)},
    flankLeftLower: {lines:['left flank','lower'],  dir:'left',  cat:'quad', ...P(2.5,7.61)},
    flankRightLower:{lines:['right flank','lower'], dir:'right', cat:'quad', ...P(8.5,7.61)}
  };
  const FULL_NAME={ringTop:'ring top',ringBottom:'ring bottom',ringLeft:'ring left',ringRight:'ring right',
    stripeUpper:'stripe upper',stripeLower:'stripe lower',flankLeftUpper:'left flank upper',flankRightUpper:'right flank upper',
    flankLeftLower:'left flank lower',flankRightLower:'right flank lower'};
  const mirrorOf={ringLeft:'ringRight',ringRight:'ringLeft',flankLeftUpper:'flankRightUpper',flankRightUpper:'flankLeftUpper',
    flankLeftLower:'flankRightLower',flankRightLower:'flankLeftLower'};

  const PHASES=[
    {key:'flood', name:'Flood', range:'it. 0–301',   color:'var(--flood)'},
    {key:'clear', name:'Clear', range:'it. 301–504', color:'var(--clear)'}
  ];

  // the trained code's own ten biggest transfers (the five biggest of each phase), read from its relay by assembleRelayLoopStripesData11x11.py; every other
  // ring code's "top 3" lens is the top three of each phase, picked the same automatic way, so that lens is honestly what the numbers rank highest. The
  // "tracked" lens reads these same ten pairs off every other code instead, for direct comparison.
  const TRAINED_EDGES=RL.trainedEdges.map(e=>({from:e.from, to:e.to, phase:e.phase, value:e.value, bow:1, trend:e.trend}));

  // Generated by buildRelayLoopArtifact.py (into the placeholders below): every other ring code's top-3-per-phase (discrete steering/knockout variants), region
  // names already mapped to node keys above.
  const VARIANT_DATA = RL.variantData;

  // Generated by buildRelayLoopArtifact.py: the two-sided sliders (one per order) and the 5 x 5 two-order grids, top-3-per-phase.
  const SLIDER_DATA = RL.sliderData;
  const GRID_DATA = RL.gridData;

  // REPLACED_AT_BUILD: computeBoundaryHarmonicRelayTrackedEdges11x11.py's output for every non-trained dataset
  // key used above -- the trained code's own eleven specific pairs, read off that code's raw relay, in
  // TRAINED_EDGES' order, as {value, reversed}. "trained" itself needs no entry: it IS TRAINED_EDGES.
  const TRACKED_DATA = RL.trackedData;

  // REPLACED_AT_BUILD: the trained code's own top-3-per-phase (computeBoundaryHarmonicRelayVariantPhaseSummary
  // 11x11.py --variantKey trained), the same automatic method every other code's "top 3" lens uses -- kept
  // separate from TRAINED_EDGES (the hand-picked eleven), which is now only ever shown by the "tracked" lens.
  const TRAINED_TOP3_PHASES = RL.trainedTop3Phases;

  // REPLACED_AT_BUILD: extractBoundaryHarmonicRelayVmemSnapshots11x11.py's output -- the tissue's Vmem (mV, one
  // decimal, 121 cells row by row) at the end of each phase, for the trained code and every other code by key.
  const VMEM_DATA = RL.vmemData;
  const CONDUCTANCE_DATA = RL.conductanceData;

  // the trained model's own largest transfer across all three phases: the fixed reference every ring code's
  // width and particle density is scaled against, so a bigger number always looks bigger, not just bigger
  // relative to whatever else that one run happened to produce.
  // ---------------- curvature policy: one fixed shape per (node pair, phase) ----------------
  // An edge's identity, for comparing ring codes by eye, is its unordered node pair and its phase (the colour). Each
  // such identity has one lane -- how far, and to which side, it bows -- fixed for every ring code, either lens and
  // either direction: the same pair in the same phase is the same curve in every panel, so a missing, added or
  // reversed edge is the only thing that changes. Two phases between the same pair take different lanes, so they
  // never share a curve. The lane is set in the pair's canonical direction (node order below) and flipped when the
  // edge runs the other way, so reversing an arrow keeps its curve. EDGE_LANES is chosen once by
  // optimizeRelayLoopEdgeLanes.py to keep edges apart in every view this page can show; a pair it has never seen
  // falls back to its phase's default lane.
  const NODE_ORDER=Object.keys(NODES);
  const EDGE_LANES = RL.edgeLanes;
  function laneBow(from, to, phase){
    const forward = NODE_ORDER.indexOf(from) < NODE_ORDER.indexOf(to);
    const key = (forward ? [from,to] : [to,from]).join('|');
    const lane = (EDGE_LANES.lanes[key]||{})[phase] ?? EDGE_LANES.default[phase];
    return lane*(forward ? 1 : -1);
  }
  TRAINED_EDGES.forEach(e=>{ e.bow=laneBow(e.from,e.to,e.phase); });      // the hand-picked eleven take their lanes too
  const TRAINED_MAX = Math.max(...TRAINED_EDGES.map(e=>e.value));
  const SCALE_CAP = 3;                       // the trained code's own largest edge should already use most of the width range (that is the "perfect" look to match); 3x that is already "much bigger", and past it the line just stays at the cap
  function scaled(value){ return Math.min(1, value/(TRAINED_MAX*SCALE_CAP)); }
  // The tracked lens holds the same eleven pairs fixed, so what a panel can show is how big each one is and which way
  // it runs. Most of those values are far below the trained code's own, where a linear width squashes them all onto
  // the thinnest line, so this lens draws width on a log scale: TRACKED_FLOOR (1% of the trained code's largest edge)
  // is the thinnest line, SCALE_CAP times that largest edge the thickest, and a tenth of a transfer is visibly thinner.
  const TRACKED_FLOOR = TRAINED_MAX*0.01;
  function normOf(value){
    if(lens!=='tracked') return scaled(value);
    const lo=Math.log(TRACKED_FLOOR), hi=Math.log(TRAINED_MAX*SCALE_CAP);
    return Math.max(0, Math.min(1, (Math.log(Math.max(value,1e-12))-lo)/(hi-lo)));
  }

  // turns one ring code's {flood,clear,write: [{from,to,value,mirrored}]} into this page's EDGES shape: a bow that
  // alternates when the same undirected pair recurs (so a reversal, or a repeat, visibly splits into two arcs
  // instead of drawing one over the other), and a trend line naming the pair's rank so the table stays honest
  // about how each row was picked.
  function edgesFromPhases(phases){
    const out=[];
    PHASES.forEach(p=>{
      (phases[p.key]||[]).forEach((e,i)=>{
        out.push({from:e.from, to:e.to, phase:p.key, value:e.value, bow:laneBow(e.from,e.to,p.key),
          trend:`${e.mirrored?'mirrored; ':'no mirror twin (both ends self-symmetric); '}rank ${i+1} of ${p.name.toLowerCase()} by size`});
      });
    });
    return out;
  }
  // the "tracked" lens: the trained code's own eleven specific pairs, values substituted from whichever code
  // "key" names -- for "trained" itself this is TRAINED_EDGES verbatim. A pair drawn with the arrow reversed
  // relative to TRAINED_EDGES keeps that template's bow, so the same pair always occupies the same visual slot
  // across every code, reversed or not.
  function trackedEdgesFor(key){
    return TRAINED_EDGES.map((template,i)=>{
      const entry = key==='trained' ? {value:template.value, reversed:false} : TRACKED_DATA[key][i];
      const from = entry.reversed ? template.to : template.from;
      const to   = entry.reversed ? template.from : template.to;
      return {from, to, phase:template.phase, value:entry.value, bow:laneBow(from,to,template.phase), reversed:!!entry.reversed,
        trend:`tracking the trained code's own row ${i+1}${entry.reversed ? ' — reversed here relative to trained' : ''}`};
    });
  }
  // mirroring a canonical edge must be a true geometric reflection: flip which way it bows, or the mirror
  // twin curves the same absolute way as the original instead of the opposite way, and the pair looks lopsided.
  function mirrorEdge(e){
    const mf=mirrorOf[e.from]||e.from, mt=mirrorOf[e.to]||e.to;
    if(mf===e.from && mt===e.to) return null;
    return Object.assign({},e,{from:mf,to:mt,bow:-(e.bow ?? 1),mirrorOfPair:true});
  }
  function allEdgesOf(edges){ return edges.concat(edges.map(mirrorEdge).filter(Boolean)); }
  let lens='top3', EDGES=TRAINED_EDGES, ALL_EDGES=allEdgesOf(EDGES);
  let currentKey='trained', currentPhases=null, currentFan=null;   // currentFan: the slider's stops (their dataset keys), else null      // the dataset on show: the lens toggle and the Vmem backdrop both read it
  const phaseByKey=Object.fromEntries(PHASES.map(p=>[p.key,p]));

  // ---------------- SVG network (the static picture: frame, arcs, nodes) ----------------
  const svg=document.getElementById('rlNet');
  const NS='http://www.w3.org/2000/svg';
  const el=(tag,attrs,parent)=>{const n=document.createElementNS(NS,tag);for(const k in attrs)n.setAttribute(k,attrs[k]);(parent||svg).appendChild(n);return n;};

  // Vmem backdrop: 121 cells on the same M/CM grid the nodes use, shaded by Vmem (white ~ -5 mV depolarized,
  // black ~ -55 mV hyperpolarized), created first so the frame, arcs and nodes all draw over it. Filled in by
  // updateBackdrop() below. The face's cells are outlined so the features stay findable where Vmem alone
  // doesn't mark them.
  const VMEM_LO=-55, VMEM_HI=-5;
  const PHASE_END_ITERATION={flood:301, clear:504};
  const FACE_CELLS=D.targetCells;        // the 27 centre-stripe cells
  function grayOf(mV){ const t=Math.max(0,Math.min(1,(mV-VMEM_HI)/(VMEM_LO-VMEM_HI))); const g=Math.round(246-214*t); return `rgb(${g},${g},${g})`; }
  const backdropGroup=el('g',{id:'rlVmemBackdrop','shape-rendering':'crispEdges',opacity:0.55});
  const backdropCells=[];
  for(let i=0;i<121;i++){ const r=Math.floor(i/11), c=i%11;
    backdropCells.push(el('rect',{x:M+c*CM,y:M+r*CM,width:CM,height:CM,fill:'none','data-cell':i},backdropGroup)); }
  const faceOutline=el('g',{fill:'none',stroke:'var(--ink-2)','stroke-width':1.2,opacity:0.5});
  FACE_CELLS.forEach(i=>{ const r=Math.floor(i/11), c=i%11; el('rect',{x:M+c*CM,y:M+r*CM,width:CM,height:CM},faceOutline); });

  // reference frame: the ring's own outer edge and the interior it encloses, faint. The grid is 11 cells across;
  // the interior (inside the ring) is the 9 cells the ring doesn't cover.
  el('rect',{x:M,y:M,width:11*CM,height:11*CM,fill:'none',stroke:'var(--line)','stroke-width':1});
  el('rect',{x:M+CM,y:M+CM,width:9*CM,height:9*CM,fill:'none',stroke:'var(--line)','stroke-width':1,'stroke-dasharray':'3 3'});

  // arrow markers, one per phase colour, open chevron. markerUnits="userSpaceOnUse" pins the head to a fixed
  // size regardless of the shaft's own stroke width -- left at the SVG default (markerUnits="strokeWidth"), a
  // thick shaft (a knockout's much larger transfer) blows the head up by the same factor, so a 10x thicker line
  // got a head with 10x the area: unreadable. Width alone now carries magnitude; the head only ever marks direction.
  const defs=el('defs',{});
  PHASES.forEach(p=>{
    const m=document.createElementNS(NS,'marker');
    m.setAttribute('id','rlArrow-'+p.key); m.setAttribute('viewBox','0 0 10 10'); m.setAttribute('refX','8'); m.setAttribute('refY','5');
    m.setAttribute('markerWidth','9'); m.setAttribute('markerHeight','9'); m.setAttribute('markerUnits','userSpaceOnUse'); m.setAttribute('orient','auto-start-reverse');
    const casing=document.createElementNS(NS,'polyline');          // the arrowhead's casing, only while the backdrop is on (see #net.withBackdrop)
    casing.setAttribute('points','1,1 8.5,5 1,9'); casing.setAttribute('class','markerCasing'); casing.setAttribute('fill','none'); casing.setAttribute('stroke','var(--surface)');
    casing.setAttribute('stroke-width','4.6'); casing.setAttribute('stroke-linecap','round'); casing.setAttribute('stroke-linejoin','round'); m.appendChild(casing);
    const poly=document.createElementNS(NS,'polyline');
    poly.setAttribute('points','1,1 8.5,5 1,9'); poly.setAttribute('fill','none'); poly.setAttribute('stroke',p.color);
    poly.setAttribute('stroke-width','2'); poly.setAttribute('stroke-linecap','round'); poly.setAttribute('stroke-linejoin','round');
    m.appendChild(poly); defs.appendChild(m);
  });

  const casingGroup=el('g',{});             // a thin casing of the page colour under each edge, shown while the Vmem backdrop is
  const edgeGroup=el('g',{});
  function computePath(e){
    const a=NODES[e.from], b=NODES[e.to];
    const dx=b.x-a.x, dy=b.y-a.y, len=Math.hypot(dx,dy), ux=dx/len, uy=dy/len, nx=-uy, ny=ux;
    const bow=(e.bow ?? 1)*Math.min(40, 14+len*0.12);
    const rA=17, rB=17, tailGap=rA+4, headGap=rB+9;
    const sx=a.x+ux*tailGap, sy=a.y+uy*tailGap, ex=b.x-ux*headGap, ey=b.y-uy*headGap;
    const mx=(sx+ex)/2+nx*bow, my=(sy+ey)/2+ny*bow;
    return {sx,sy,mx,my,ex,ey};
  }
  // width (and, further down, particle density) is scaled to the TRAINED code's own largest transfer, fixed --
  // not to whichever ring code is currently drawn. A knockout can carry a transfer a hundred times the trained
  // scale; past SCALE_CAP times that reference the line simply stops growing, at the width the trained code's
  // own strongest edge already uses, so a huge value reads as "off the trained scale", not as a solid block.
  function drawArcs(){
    while(edgeGroup.firstChild) edgeGroup.removeChild(edgeGroup.firstChild);
    while(casingGroup.firstChild) casingGroup.removeChild(casingGroup.firstChild);
    ALL_EDGES.forEach(e=>{
      e.path=computePath(e);
      e.norm=normOf(e.value);
      const {sx,sy,mx,my,ex,ey}=e.path, w=1.6+8.4*e.norm, dashed=lens==='tracked' && e.reversed;   // dashed: runs the opposite way from the trained code
      el('path',{d:`M ${sx.toFixed(1)} ${sy.toFixed(1)} Q ${mx.toFixed(1)} ${my.toFixed(1)} ${ex.toFixed(1)} ${ey.toFixed(1)}`,fill:'none',stroke:'var(--surface)','stroke-width':(w+5).toFixed(2),
        'stroke-linecap':'round','data-casing':e.phase,class:'edgeCasing'}, casingGroup);
      e.el=el('path',{d:`M ${sx.toFixed(1)} ${sy.toFixed(1)} Q ${mx.toFixed(1)} ${my.toFixed(1)} ${ex.toFixed(1)} ${ey.toFixed(1)}`,
        fill:'none',stroke:`var(--${e.phase})`,'stroke-width':w.toFixed(2),'stroke-linecap':dashed?'butt':'round','stroke-dasharray':dashed?`${(w*2.2).toFixed(1)} ${(w*1.6).toFixed(1)}`:'none','marker-end':`url(#rlArrow-${e.phase})`,
        'data-phase':e.phase,opacity:0.6}, edgeGroup);
    });
  }
  drawArcs();

  // nodes on top, each label placed outward from the grid so it never runs into the busy interior
  const catColor={ring:'var(--ring)',quad:'var(--quad)',feature:'var(--feature)'};
  // A node is a light disc outlined in its category colour, inside a thin halo of the page colour. The Vmem shading puts black cells (the
  // hyperpolarized face) behind the nodes, so a node must never be dark itself, or it merges with the tissue under it.
  function drawNode(parent, n, r, strokeWidth){
    el('circle',{cx:n.x,cy:n.y,r:r+2.5,fill:'none',stroke:'var(--surface)','stroke-width':3,opacity:0.9},parent);
    return el('circle',{cx:n.x,cy:n.y,r,fill:'var(--node-fill)',stroke:catColor[n.cat],'stroke-width':strokeWidth},parent);
  }
  const nodeGroup=el('g',{});
  const LH=12;
  Object.entries(NODES).forEach(([key,n])=>{
    drawNode(nodeGroup, n, 15, 2.6);
    const mk=(x,y,anchor,word)=>el('text',{x,y,'text-anchor':anchor,'font-family':"'IBM Plex Mono',monospace",'font-size':10.5,fill:'var(--ink-2)',stroke:'var(--surface)','stroke-width':3,'paint-order':'stroke','stroke-linejoin':'round'},nodeGroup).textContent=word;
    const N=n.lines.length;
    if(n.dir==='above') n.lines.forEach((w,i)=>mk(n.x, n.y-18-(N-1-i)*LH, 'middle', w));
    else if(n.dir==='below') n.lines.forEach((w,i)=>mk(n.x, n.y+28+i*LH, 'middle', w));
    else if(n.dir==='left') n.lines.forEach((w,i)=>mk(n.x-20, n.y+4+(i-(N-1)/2)*LH, 'end', w));
    else n.lines.forEach((w,i)=>mk(n.x+20, n.y+4+(i-(N-1)/2)*LH, 'start', w));
  });

  // ---------------- particle flow: canvas layer over the SVG, phase-sequenced by default ----------------
  const wrap=svg.parentNode;
  const canvas=document.createElement('canvas'); canvas.className='flowLayer'; wrap.appendChild(canvas);
  const ctx=canvas.getContext ? canvas.getContext('2d') : null;
  const VB_X=-6, VB_Y=36, VB_W=640, VB_H=568;   // must match the svg viewBox above
  function placeCanvas(){
    const box=svg.getBoundingClientRect(); if(!box.width) return;
    const ratio=window.devicePixelRatio||1;
    canvas.style.width=box.width+'px'; canvas.style.height=box.height+'px';
    canvas.width=Math.max(1,Math.round(box.width*ratio)); canvas.height=Math.max(1,Math.round(box.height*ratio));
  }
  window.addEventListener('resize', placeCanvas);
  if(typeof ResizeObserver!=='undefined') new ResizeObserver(placeCanvas).observe(svg);
  placeCanvas();

  const cssColor=name=>(window.getComputedStyle?getComputedStyle(document.documentElement).getPropertyValue(name):'').trim();
  const refreshColors=()=>{PHASES.forEach(p=>{p.rgb=cssColor('--'+p.key);});};
  refreshColors();
  if(window.matchMedia){
    const mq=window.matchMedia('(prefers-color-scheme: dark)');
    (mq.addEventListener?mq.addEventListener.bind(mq):mq.addListener.bind(mq))('change',refreshColors);
  }

  const reduceMotion=!!(window.matchMedia && window.matchMedia('(prefers-reduced-motion: reduce)').matches);
  const SPAWN=26, SPEED=0.55, FADE=0.5, HEAD_R=2.8;
  // each phase streams for STREAM seconds, then nothing spawns for REST seconds -- long enough for a particle's
  // whole 1/SPEED-second trip plus its fading trail to clear the canvas before the next phase's particles begin.
  // The same rest follows the write phase too, so the pause between loops is exactly as generous.
  const STREAM=2.8, REST=3.2;
  PHASES.forEach((p,i)=>{ p.tStart=i*(STREAM+REST); p.tEnd=p.tStart+STREAM; });
  const CYCLE=PHASES.length*(STREAM+REST);
  let cycleT=0, particles=[], lastStamp=null, activeKey=null;

  function phaseAt(t){ for(const p of PHASES) if(t>=p.tStart && t<p.tEnd) return p.key; return null; }

  function step(dt){
    if(!activeKey) cycleT=(cycleT+dt)%CYCLE;
    ALL_EDGES.forEach(e=>{
      const active = activeKey ? e.phase===activeKey : e.phase===phaseAt(cycleT);
      if(active){
        e.acc=(e.acc||0)+SPAWN*e.norm*dt;
        while(e.acc>=1 && particles.length<400){ e.acc-=1; particles.push({e,s:0}); }
      }
    });
    particles=particles.filter(pt=>{pt.s+=SPEED*dt; return pt.s<1;});
  }

  function paint(dt){
    if(!ctx || !canvas.width) return;
    const k=canvas.width/VB_W, ox=-VB_X*k, oy=-VB_Y*k;     // svg-space -> canvas pixels: shift by the viewBox origin, then scale
    ctx.globalCompositeOperation='destination-out';
    ctx.fillStyle='rgba(0,0,0,'+(1-Math.exp(-dt/FADE)).toFixed(4)+')';
    ctx.fillRect(0,0,canvas.width,canvas.height);
    ctx.globalCompositeOperation='source-over';
    particles.forEach(pt=>{
      const {sx,sy,mx,my,ex,ey}=pt.e.path, t=pt.s, u=1-t;
      const x=(u*u*sx+2*u*t*mx+t*t*ex)*k+ox, y=(u*u*sy+2*u*t*my+t*t*ey)*k+oy;
      ctx.beginPath(); ctx.arc(x,y,HEAD_R*k,0,Math.PI*2);
      ctx.fillStyle=phaseByKey[pt.e.phase].rgb||'#888'; ctx.fill();
    });
  }

  function loop(stamp){
    requestAnimationFrame(loop);
    const dt = lastStamp===null?0:Math.min(0.05,(stamp-lastStamp)/1000); lastStamp=stamp;
    step(dt); paint(dt); updateRibbonLive();
  }
  if(!reduceMotion && ctx) requestAnimationFrame(loop);

  // ---------------- Vmem backdrop: follows the live phase and the ring code on show ----------------
  // The phase shown is the isolated one, else the one whose particles are streaming; in the rests between
  // phases it holds the last one, so the picture never blanks. Redrawn only when the code, the phase or the
  // checkbox changed (this runs on the toggle row's 120 ms tick too); the colours ease over in CSS.
  const vmemToggle=document.getElementById('rlVmemToggle'), vmemNote=document.getElementById('rlVmemNote');
  vmemToggle.checked=true;
  let lastBackdropPhase='flood', drawnBackdrop='';
  function updateBackdrop(){
    const on=vmemToggle.checked;
    backdropGroup.style.display = faceOutline.style.display = casingGroup.style.display = on ? '' : 'none';
    if(on) svg.classList.add('withBackdrop'); else svg.classList.remove('withBackdrop');       // lets the arrowheads' casing show too
    if(!on){ vmemNote.textContent=''; drawnBackdrop=''; return; }
    const live = activeKey || (reduceMotion || !ctx ? null : phaseAt(cycleT));
    if(live) lastBackdropPhase=live;
    const phase=lastBackdropPhase, tag=currentKey+'|'+phase;
    if(tag===drawnBackdrop) return;
    drawnBackdrop=tag;
    const codeSnaps=VMEM_DATA[currentKey];
    if(!codeSnaps){ vmemNote.textContent='no Vmem stored for this ring code'; return; }
    const snap=codeSnaps[phase];
    backdropCells.forEach((rect,i)=>{ rect.style.fill=grayOf(snap[i]); });
    vmemNote.textContent=`tissue Vmem at the end of ${phase} (iteration ${PHASE_END_ITERATION[phase]}): white \u2248 \u22125 mV, black \u2248 \u221255 mV`;
  }
  vmemToggle.addEventListener('change',()=>{ drawnBackdrop=''; updateBackdrop(); });

  // ---------------- conductance ribbon: mean G_pol / G_ref, feature cells against the rest of the interior ----------------
  // The same two curves as figure 2 of the latching-switch report (14 feature cells, 67 other interior cells), cut off at
  // the write peak (iteration 1765), for whichever ring code is on show, with the trained code dashed behind it.
  const COND=CONDUCTANCE_DATA, COND_ITER=COND.states.map(st=>st-1);
  const RIB={x0:54, x1:598, y0:30, y1:150, end:504};
  const PHASE_SPANS={flood:[0,301], clear:[301,504]};
  const ribbonSvg=document.getElementById('rlRibbon'), ribbonDelta=document.getElementById('rlRibbonDelta'), ribbonNote=document.getElementById('rlRibbonNote');
  const rText=(str,attrs,parent)=>{ const n=el('text',attrs,parent); n.textContent=str; return n; };
  const rx=it=>RIB.x0+it/RIB.end*(RIB.x1-RIB.x0);
  const fmtSigned=v=>(v>=0?'+':'')+v.toFixed(3);
  const subtract=(a,b)=>a.map((v,i)=>v-b[i]);
  const gapOfCurves=c=>c.featureMean[c.featureMean.length-1]-c.backgroundMean[c.backgroundMean.length-1];
  let ribbonBands={}, ribbonBandLabels={}, ribbonPlayhead=null, ribbonDots=null, ribbonShown=null, ribbonY=null;

  function renderRibbon(){
    while(ribbonSvg.firstChild) ribbonSvg.removeChild(ribbonSvg.firstChild);
    const cur=COND.curves[currentKey], trained=COND.curves.trained, delta=ribbonDelta.checked;
    const fanKeys=currentFan ? currentFan.filter(k=>k!==currentKey) : [];
    const shownKeys=[currentKey, ...fanKeys];
    let lo=0.2, hi=1.8, step=0.2;
    if(delta){
      let worst=0.1;
      shownKeys.forEach(k=>['featureMean','backgroundMean'].forEach(f=>subtract(COND.curves[k][f],trained[f]).forEach(v=>{ worst=Math.max(worst,Math.abs(v)); })));
      hi=Math.ceil(worst*10)/10; lo=-hi; step=hi>0.5?0.5:0.1*Math.max(1,Math.round(hi*10/4));
    }
    const ry=v=>RIB.y1-(v-lo)/(hi-lo)*(RIB.y1-RIB.y0); ribbonY=ry;
    const defs=el('defs',{},ribbonSvg);
    const clip=el('clipPath',{id:'rlRibbonClip'},defs); el('rect',{x:RIB.x0,y:RIB.y0,width:RIB.x1-RIB.x0,height:RIB.y1-RIB.y0},clip);
    // phase bands
    ribbonBands={}; ribbonBandLabels={};
    PHASES.forEach(ph=>{
      const [a,b]=PHASE_SPANS[ph.key];
      ribbonBands[ph.key]=el('rect',{x:rx(a),y:RIB.y0,width:rx(b)-rx(a),height:RIB.y1-RIB.y0,fill:ph.color,'fill-opacity':0.07},ribbonSvg);
      ribbonBandLabels[ph.key]=rText(ph.name,{x:(rx(a)+rx(b))/2,y:RIB.y0-9,'text-anchor':'middle','font-size':10.5,fill:ph.color},ribbonSvg);
    });
    // axes
    for(let v=Math.ceil(lo/step-1e-9)*step; v<=hi+1e-9; v+=step){
      el('line',{x1:RIB.x0,x2:RIB.x1,y1:ry(v),y2:ry(v),stroke:'var(--line-soft)','stroke-width':Math.abs(v)<1e-9&&delta?1.4:0.8},ribbonSvg);
      rText(Math.abs(v)<1e-9?'0':v.toFixed(step<0.1?2:1),{x:RIB.x0-6,y:ry(v)+3.5,'text-anchor':'end','font-size':9.5,fill:'var(--ink-3)'},ribbonSvg);
    }
    rText(delta?'Δ G_pol / G_ref':'G_pol / G_ref',{x:12,y:(RIB.y0+RIB.y1)/2,'text-anchor':'middle','font-size':10,fill:'var(--ink-2)',transform:`rotate(-90 12 ${(RIB.y0+RIB.y1)/2})`},ribbonSvg);
    [0,100,200,301,400,504].forEach(it=>{
      el('line',{x1:rx(it),x2:rx(it),y1:RIB.y1,y2:RIB.y1+4,stroke:'var(--ink-3)'},ribbonSvg);
      rText(String(it),{x:rx(it),y:RIB.y1+15,'text-anchor':'middle','font-size':9.5,fill:'var(--ink-3)'},ribbonSvg);
    });
    rText('iteration',{x:RIB.x1,y:RIB.y1+28,'text-anchor':'end','font-size':9.5,fill:'var(--ink-2)'},ribbonSvg);
    el('line',{x1:RIB.x0,x2:RIB.x1,y1:RIB.y1,y2:RIB.y1,stroke:'var(--ink-3)'},ribbonSvg);
    // series
    const plot=el('g',{'clip-path':'url(#rlRibbonClip)'},ribbonSvg);
    const path=(vals,attrs)=>el('path',Object.assign({d:vals.map((v,i)=>`${i?'L':'M'}${rx(COND_ITER[i]).toFixed(1)} ${ry(v).toFixed(1)}`).join(' '),fill:'none','stroke-linejoin':'round'},attrs),plot);
    const area=(top,bottom,colour,opacity)=>el('path',{d:top.map((v,i)=>`${i?'L':'M'}${rx(COND_ITER[i]).toFixed(1)} ${ry(v).toFixed(1)}`).join(' ')
      +bottom.slice().reverse().map((v,i)=>`L${rx(COND_ITER[COND_ITER.length-1-i]).toFixed(1)} ${ry(v).toFixed(1)}`).join(' ')+'Z',fill:colour,'fill-opacity':opacity,stroke:'none'},plot);
    const seriesOf=(c,field)=>delta ? subtract(c[field],trained[field]) : c[field];
    const featureNow=seriesOf(cur,'featureMean'), backgroundNow=seriesOf(cur,'backgroundMean');
    if(!delta){
      area(cur.backgroundMax,cur.backgroundMin,'var(--background)',0.07);
      area(cur.featureMax,cur.featureMin,'var(--feature)',0.09);
      area(featureNow,backgroundNow,'var(--feature)',0.10);
    }
    fanKeys.forEach(k=>{
      path(seriesOf(COND.curves[k],'backgroundMean'),{stroke:'var(--background)','stroke-width':1,'stroke-opacity':0.5});
      path(seriesOf(COND.curves[k],'featureMean'),{stroke:'var(--feature)','stroke-width':1,'stroke-opacity':0.5});
    });
    if(!delta && !currentFan && currentKey!=='trained'){
      path(trained.backgroundMean,{stroke:'var(--background)','stroke-width':1.3,'stroke-dasharray':'4 3','stroke-opacity':0.85});
      path(trained.featureMean,{stroke:'var(--feature)','stroke-width':1.3,'stroke-dasharray':'4 3','stroke-opacity':0.85});
    }
    path(backgroundNow,{stroke:'var(--background)','stroke-width':2});
    path(featureNow,{stroke:'var(--feature)','stroke-width':2.4});
    // slider stops labelled by t at the right edge, on the feature curve
    if(currentFan){
      const order=sliderOrderSelect.value, points=SLIDER_DATA[order].points;
      // labels sit at each stop's end value, pushed apart so stops that finish close together stay readable
      const labels=points.filter(pt=>pt.key===currentKey||pt.key==='trained'||pt===points[0]||pt===points[points.length-1]).map(pt=>{ const last=seriesOf(COND.curves[pt.key],'featureMean'); return {pt, y:ry(Math.max(lo,Math.min(hi,last[last.length-1])))}; }).sort((a,b)=>a.y-b.y);
      for(let i=1;i<labels.length;i++) labels[i].y=Math.max(labels[i].y, labels[i-1].y+9);
      labels.forEach(({pt,y})=>{
        rText(pt.key==='trained'?'trained':pt.knockout?'ko':signed(pt.offset),{x:RIB.x1+3,y:y+3,'font-size':8.5,fill:pt.key===currentKey?'var(--ink)':'var(--ink-3)','font-weight':pt.key===currentKey?700:400},ribbonSvg);
      });
    }
    // legend
    const ly=RIB.y1+46;
    [['stripe cells (27)','var(--feature)',RIB.x0,false],['flank cells (54)','var(--background)',RIB.x0+160,false]].forEach(([label,colour,x])=>{
      el('line',{x1:x,x2:x+18,y1:ly,y2:ly,stroke:colour,'stroke-width':2.2},ribbonSvg); rText(label,{x:x+24,y:ly+3.5,'font-size':9.5,fill:'var(--ink-2)'},ribbonSvg);
    });
    if(!delta && !currentFan){
      el('line',{x1:RIB.x0+360,x2:RIB.x0+378,y1:ly,y2:ly,stroke:'var(--ink-3)','stroke-width':1.3,'stroke-dasharray':'4 3'},ribbonSvg);
      rText('trained code',{x:RIB.x0+384,y:ly+3.5,'font-size':9.5,fill:'var(--ink-2)'},ribbonSvg);
    }
    // playhead: a line and a dot on each mean, moved every frame by updateRibbonLive
    ribbonPlayhead=el('line',{x1:0,x2:0,y1:RIB.y0,y2:RIB.y1,stroke:'var(--ink)','stroke-width':1,'stroke-opacity':0.6,visibility:'hidden'},ribbonSvg);
    ribbonDots=[el('circle',{r:3.4,fill:'var(--feature)',stroke:'var(--surface)','stroke-width':1.2,visibility:'hidden'},ribbonSvg),
                el('circle',{r:3.4,fill:'var(--background)',stroke:'var(--surface)','stroke-width':1.2,visibility:'hidden'},ribbonSvg)];
    ribbonShown={feature:featureNow, background:backgroundNow};
    ribbonNote.textContent = `selectivity gap at iteration 504 ${fmtSigned(gapOfCurves(cur))}`
      + (currentKey==='trained' ? ' (the trained code)' : ` · trained ${fmtSigned(gapOfCurves(trained))}`);
    updateRibbonLive();
  }
  ribbonDelta.addEventListener('change',renderRibbon);

  function valueAt(series, it){
    let i=0; while(i<COND_ITER.length-2 && COND_ITER[i+1]<it) i++;
    const f=(it-COND_ITER[i])/(COND_ITER[i+1]-COND_ITER[i]);
    return series[i]+(series[i+1]-series[i])*Math.max(0,Math.min(1,f));
  }
  // highlights the live phase's band and moves the playhead, phase by phase: a phase's stream sweeps its own iteration
  // range at the same pace whatever its length, and the marker rests at a phase's end during the pause after it.
  function updateRibbonLive(){
    if(!ribbonPlayhead) return;
    const playing = !activeKey && !reduceMotion && !!ctx;
    const live = activeKey || (playing ? phaseAt(cycleT) : null);
    PHASES.forEach(ph=>{
      ribbonBands[ph.key].setAttribute('fill-opacity', !live ? 0.07 : (ph.key===live ? 0.17 : 0.03));
      ribbonBandLabels[ph.key].setAttribute('opacity', !live || ph.key===live ? 1 : 0.45);
    });
    const vis = playing ? 'visible' : 'hidden';
    ribbonPlayhead.setAttribute('visibility',vis); ribbonDots.forEach(d=>d.setAttribute('visibility',vis));
    if(!playing) return;
    let ph=PHASES[0]; for(const q of PHASES) if(cycleT>=q.tStart) ph=q;
    const [a,b]=PHASE_SPANS[ph.key], it=a+(b-a)*Math.min(1,(cycleT-ph.tStart)/STREAM);
    const x=rx(it);
    ribbonPlayhead.setAttribute('x1',x); ribbonPlayhead.setAttribute('x2',x);
    ribbonDots[0].setAttribute('cx',x); ribbonDots[0].setAttribute('cy',ribbonY(valueAt(ribbonShown.feature,it)));
    ribbonDots[1].setAttribute('cx',x); ribbonDots[1].setAttribute('cy',ribbonY(valueAt(ribbonShown.background,it)));
  }

  // ---------------- toggle row: click a phase to isolate its own continuous flow ----------------
  const toggles=document.getElementById('rlToggles');
  function renderToggles(){
    // edges only change with a manual click (instant, same moment its particles start); the auto-cycle leaves
    // them at one constant shade throughout, since the arc lighting up a beat before any particle reaches it
    // reads as the flow arriving late, not as the arc announcing what's coming.
    edgeGroup.querySelectorAll('path').forEach(p=>{
      p.style.opacity = !activeKey ? 0.6 : (p.getAttribute('data-phase')===activeKey ? 0.95 : 0.1);
    });
    casingGroup.querySelectorAll('path').forEach(p=>{
      p.style.opacity = !activeKey ? 0.35 : (p.getAttribute('data-casing')===activeKey ? 0.8 : 0.06);   // proportional to the edge's own opacity, so a faint edge does not get a dark smudge
    });
    const shown = activeKey || (reduceMotion || !ctx ? null : phaseAt(cycleT));
    toggles.querySelectorAll('.toggle').forEach(b=>{
      b.setAttribute('data-active', (!shown || b.dataset.key===shown) ? '1' : '0');
    });
    updateBackdrop();
    updateRibbonLive();
  }
  PHASES.forEach(p=>{
    const b=document.createElement('button');
    b.className='toggle'; b.dataset.key=p.key; b.type='button';
    b.innerHTML=`<span class="dot" style="background:${p.color}"></span>${p.name} <span style="opacity:.7">${p.range}</span>`;
    b.addEventListener('click',()=>{ activeKey = (activeKey===p.key) ? null : p.key; renderToggles(); });
    toggles.appendChild(b);
  });
  setInterval(renderToggles, 120);   // keeps the toggle row's highlight following the auto-playing sequence
  renderToggles();

  // ---------------- data table ----------------
  const rows=document.getElementById('rlRows');
  function renderTable(){
    while(rows.firstChild) rows.removeChild(rows.firstChild);
    EDGES.forEach(e=>{
      const ph=phaseByKey[e.phase];
      const tr=document.createElement('tr');
      const offScale = e.value > TRAINED_MAX*SCALE_CAP;
      tr.innerHTML=`<td class="phase"><span class="swatch" style="background:${ph.color}"></span>${ph.name}</td>`
        +`<td>${FULL_NAME[e.from]} &rarr; ${FULL_NAME[e.to]}</td>`
        +`<td class="num">${e.value.toFixed(3)}${offScale?' <span title="drawn at the maximum width">(off the trained scale)</span>':''}</td>`
        +`<td>${e.trend}</td>`;
      rows.appendChild(tr);
    });
  }
  renderTable();

  function refreshDiagram(){
    ALL_EDGES=allEdgesOf(EDGES);
    particles=[]; if(ctx) ctx.clearRect(0,0,canvas.width,canvas.height);
    drawArcs(); renderTable(); renderToggles();
  }

  // ---------------- lens: top-3-per-phase (each code's own) vs tracked (trained's fixed 11, everywhere) ----------------
  // whichever mode is active, currentKey/currentPhases record what is currently shown so the lens toggle alone
  // can redraw it without each mode needing to know about the other two.
  const lensSelect=document.getElementById('rlLens'), lensNote=document.getElementById('rlLensNote');
  function edgesForCurrent(){
    // "tracked" always reads the fixed eleven off whichever code is current (trackedEdgesFor('trained') is
    // TRAINED_EDGES itself, by construction); "top 3" is that code's own automatic top-3-per-phase, trained
    // code included -- TRAINED_EDGES is reserved for the tracked lens' template, never shown under "top 3".
    if(lens==='tracked') return trackedEdgesFor(currentKey);
    return edgesFromPhases(currentPhases);
  }
  function showDataset(key, phases, fan){
    currentKey=key; currentPhases=phases; currentFan=fan||null;
    EDGES=edgesForCurrent();
    refreshDiagram();
    renderRibbon();
  }
  // mode (declared below, with the mode switch) isn't initialized yet at this point in the script, so this
  // handler only ever runs later, from a real change event or setMode's own call after mode exists.
  function applyLens(){
    lens=lensSelect.value;
    lensNote.textContent = lens==='tracked'
      ? 'every panel now reads the same ten pairs the trained code uses, even where they are small or run backwards here; width is on a log scale and a dashed line runs the opposite way from the trained code'
      : 'every panel shows its own three biggest movers per phase, which can be different pairs from one code to the next';
    EDGES=edgesForCurrent();
    refreshDiagram();
    if(mode==='grid') renderGridThumbnails();
  }
  lensSelect.addEventListener('change',applyLens);
  lensNote.textContent='every panel shows its own three biggest movers per phase, which can be different pairs from one code to the next';

  // ---------------- mode switch: a single ring code, the trained-to-knockout slider, or the two-order grid ----------------
  const MODES=[{key:'single',name:'Single ring code'},{key:'slider',name:'Slider: one order at a time'},{key:'grid',name:'Grid: two orders at once'}];
  const modesEl=document.getElementById('rlModes'), singleControls=document.getElementById('rlSingleControls'),
        sliderControls=document.getElementById('rlSliderControls'), gridFigure=document.getElementById('rlGridFigure'),
        modeExplainer=document.getElementById('rlModeExplainer');
  const EXPLAIN={
    single:'Pick the trained code or any of the curated variants (each order knocked out, the uniform ring, the four ring codes of the ends test) and see its own loop.',
    slider:'Drag along one order’s coefficient. The stops are the trained value plus an offset from −0.6 to +0.6, packed closely near the trained value because the window the stripe forms in is a few thousandths wide, plus the order’s knockout (coefficient 0) where it is not already a stop. Ring values are clipped to 0–2 G_pol / G_ref. A relay was actually run at each stop, spaced by run, not by value: this is not a visual interpolation.',
    grid:'Twenty-five small diagrams: two orders each moved through five offsets (−0.30, −0.08, trained, +0.08, +0.30) independently, the third order at its trained value. The middle row and column are each order alone and the centre is the trained code; every other panel moves both orders.'
  };
  let mode='single';
  function setMode(key){
    mode=key;
    singleControls.hidden = key!=='single'; sliderControls.hidden = key!=='slider'; gridFigure.hidden = key!=='grid';
    modesEl.querySelectorAll('.modeBtn').forEach(b=>b.setAttribute('data-active', b.dataset.key===key?'1':'0'));
    modeExplainer.textContent=EXPLAIN[key];
    if(key==='single') switchVariant(document.getElementById('rlVariant').value);
    else if(key==='slider') applySlider();
    else renderGrid();
  }
  MODES.forEach(m=>{
    const b=document.createElement('button'); b.className='modeBtn'; b.type='button'; b.dataset.key=m.key; b.textContent=m.name;
    b.addEventListener('click',()=>setMode(m.key)); modesEl.appendChild(b);
  });

  // ---------------- single ring code ----------------
  const variantSelect=document.getElementById('rlVariant'), variantNote=document.getElementById('rlVariantNote');
  const VARIANT_ORDER=['trained', ...Object.keys(VARIANT_DATA)];
  VARIANT_ORDER.forEach(key=>{
    const o=document.createElement('option'); o.value=key;
    o.textContent = key==='trained' ? 'Trained code' : VARIANT_DATA[key].label;
    variantSelect.appendChild(o);
  });
  function switchVariant(key){
    showDataset(key, key==='trained' ? TRAINED_TOP3_PHASES : VARIANT_DATA[key].phases);
    variantNote.textContent = key==='trained' ? 'the stripe code, a0 1.350, a1 0.001, a2 0.137, read at iteration 504'
      : `${VARIANT_DATA[key].label.split(':')[0]} · stripe overlap ${VARIANT_DATA[key].overlap.toFixed(2)} at iteration 504 (upper ${VARIANT_DATA[key].upperDark} / lower ${VARIANT_DATA[key].lowerDark} of 12 dark)`;
  }
  variantSelect.addEventListener('change',()=>switchVariant(variantSelect.value));

  // ---------------- slider: one order's coefficient, offsets from the trained value, actually-run stops ----------------
  const signed=v=>(v>=0?'+':'\u2212')+Math.abs(v).toFixed(3);
  const clippedText=n=>n>0 ? ` · ring values clipped to 0–2 in ${n} of 40 ring cells` : '';
  const sliderOrderSelect=document.getElementById('rlSliderOrder'), sliderT=document.getElementById('rlSliderT'), sliderReadout=document.getElementById('rlSliderReadout'), sliderNote=document.getElementById('rlSliderNote');
  Object.keys(SLIDER_DATA).forEach(order=>{
    const o=document.createElement('option'); o.value=order; o.textContent=`order ${order}`; sliderOrderSelect.appendChild(o);
  });
  const trainedStop=order=>SLIDER_DATA[order].points.findIndex(p=>p.key==='trained');
  function resetSlider(){ const order=sliderOrderSelect.value; sliderT.max=String(SLIDER_DATA[order].points.length-1); sliderT.value=String(trainedStop(order)); }   // order 0 has one more stop than the others
  resetSlider();
  function applySlider(){
    const order=sliderOrderSelect.value, points=SLIDER_DATA[order].points;   // [{offset,coefficient,phases,key,clipped,knockout,overlap,upperDark,lowerDark,gap}], ascending
    const pt=points[Math.max(0,Math.min(points.length-1,+sliderT.value))];
    showDataset(pt.key, pt.phases, points.map(q=>q.key));
    sliderReadout.textContent=`a${order} = ${pt.coefficient.toFixed(4)} · ${pt.key==='trained'?'trained':pt.knockout?'knockout':'offset '+signed(pt.offset)}`;
    sliderNote.textContent = `at iteration 504: stripe overlap ${pt.overlap.toFixed(2)}, ${pt.upperDark} of 12 upper and ${pt.lowerDark} of 12 lower stripe cells dark, selectivity gap ${fmtSigned(pt.gap)}`+clippedText(pt.clipped);
  }
  sliderOrderSelect.addEventListener('change',()=>{ resetSlider(); applySlider(); });
  sliderT.addEventListener('input',applySlider);

  // ---------------- grid: two orders, three settings each (trained / half / knocked out) ----------------
  const gridPairSelect=document.getElementById('rlGridPair'), gridWrap=document.getElementById('rlGridWrap'),
        gridRowLabels=document.getElementById('rlGridRowLabels'), gridColLabels=document.getElementById('rlGridColLabels');
  const GRID_LEVELS=RL.gridOffsets.map(o=>o===0?'trained':signed(o)), GRID_SIZE=GRID_LEVELS.length;
  Object.keys(GRID_DATA).forEach(pairKey=>{
    const [a,b]=GRID_DATA[pairKey].orders;
    const o=document.createElement('option'); o.value=pairKey; o.textContent=`order ${a} × order ${b}`;
    gridPairSelect.appendChild(o);
  });
  // Thumbnails draw their own arrowheads (a filled triangle sized to the line, so it still shows on a thick one), dashed
  // lines for edges reversed relative to the trained code (tracked lens), and, with "differences only", gray ghosts for
  // edges that match the trained code (within 2x of its value, same direction) so only what changed is in colour.
  let gridDiffOnly=false, gridShowArrows=true, gridVmem=true, gridShowNetwork=true;
  const THUMB_MAX_WIDTH=15;           // the trained code's thickest edge is about 10 here; a saturated one is drawn 1.5x that, not 2.3x
  const pairOf=e=>[e.from,e.to].sort().join('|');
  const within2x=(value,ref)=>{ const r=value/ref; return r>=0.5 && r<=2; };
  function unchangedFlags(edges){
    if(lens==='tracked') return edges.map((e,i)=>!e.reversed && within2x(e.value, TRAINED_EDGES[i].value));
    const ref=new Map(edgesFromPhases(TRAINED_TOP3_PHASES).map(t=>[pairOf(t)+'|'+t.phase, t]));
    return edges.map(e=>{ const t=ref.get(pairOf(e)+'|'+e.phase); return !!t && t.from===e.from && within2x(e.value, t.value); });
  }
  function missingFromTrained(edges){        // top-3 lens only: the trained code's edges this code does not draw at all
    if(lens==='tracked') return [];
    const have=new Set(edges.map(e=>pairOf(e)+'|'+e.phase));
    return edgesFromPhases(TRAINED_TOP3_PHASES).filter(t=>!have.has(pairOf(t)+'|'+t.phase));
  }
  function miniDiagram(edges, size, key){
    const mini=document.createElementNS(NS,'svg'); mini.setAttribute('viewBox','-6 36 640 568'); mini.setAttribute('width',size); mini.setAttribute('height',size);
    el('rect',{x:M,y:M,width:11*CM,height:11*CM,fill:'none',stroke:'var(--line)','stroke-width':2},mini);
    if(gridVmem && VMEM_DATA[key] && VMEM_DATA[key].best){          // this code's own tissue at iteration 2173, the trained code's scored moment
      const shade=el('g',{'shape-rendering':'crispEdges',class:'thumbVmem'},mini);
      VMEM_DATA[key].best.forEach((mV,i)=>el('rect',{x:M+(i%11)*CM,y:M+Math.floor(i/11)*CM,width:CM,height:CM,fill:grayOf(mV),'data-cell':i},shade));
      const outline=el('g',{fill:'none',stroke:'var(--ink-2)','stroke-width':2.5,opacity:0.55},mini);
      FACE_CELLS.forEach(i=>el('rect',{x:M+(i%11)*CM,y:M+Math.floor(i/11)*CM,width:CM,height:CM},outline));
    }
    if(!gridShowNetwork) return mini;                 // the tissue alone: no edges, no nodes
    const flags=gridDiffOnly ? unchangedFlags(edges) : null;
    const pathOf=p=>`M ${p.sx.toFixed(1)} ${p.sy.toFixed(1)} Q ${p.mx.toFixed(1)} ${p.my.toFixed(1)} ${p.ex.toFixed(1)} ${p.ey.toFixed(1)}`;
    if(gridDiffOnly) allEdgesOf(missingFromTrained(edges)).forEach(e=>{          // where the trained code had an edge and this one has none
      el('path',{d:pathOf(computePath(e)),fill:'none',stroke:'var(--ink-3)','stroke-width':4,'stroke-linecap':'round','stroke-dasharray':'2 11',opacity:0.6},mini);
    });
    allEdgesOf(edges.map((e,i)=>Object.assign({},e,{unchanged:flags?flags[i]:false}))).forEach(e=>{
      const path=computePath(e), norm=normOf(e.value), w=Math.min(THUMB_MAX_WIDTH,(1.6+8.4*norm)*2.3);
      if(e.unchanged){ el('path',{d:pathOf(path),fill:'none',stroke:'var(--ink-3)','stroke-width':4,'stroke-linecap':'round',opacity:0.35},mini); return; }
      const dashed=lens==='tracked' && e.reversed, opacity=lens==='tracked' ? 0.35+0.55*norm : 0.85, colour=`var(--${e.phase})`;
      // over the shaded tissue an edge sits in a thin casing of the page colour, so its colour reads against any gray
      if(gridVmem) el('path',{d:pathOf(path),fill:'none',stroke:'var(--surface)','stroke-width':(w+4).toFixed(2),'stroke-linecap':'round',opacity:0.78,class:'edgeCasing'},mini);
      el('path',{d:pathOf(path),fill:'none',stroke:colour,'stroke-width':w.toFixed(2),'stroke-linecap':dashed?'butt':'round',
        'stroke-dasharray':dashed?`${(w*2).toFixed(1)} ${(w*1.5).toFixed(1)}`:'none',opacity},mini);
      if(!gridShowArrows) return;       // the lines alone; a dashed line still marks a reversed edge
      const tx=path.ex-path.mx, ty=path.ey-path.my, tl=Math.hypot(tx,ty)||1, ux=tx/tl, uy=ty/tl, L=15+0.8*w, H=L*0.55;
      el('polygon',{points:`${path.ex+ux*4},${path.ey+uy*4} ${path.ex-ux*L-uy*H},${path.ey-uy*L+ux*H} ${path.ex-ux*L+uy*H},${path.ey-uy*L-ux*H}`,fill:colour,opacity,...(gridVmem?{stroke:'var(--surface)','stroke-width':4,'stroke-linejoin':'round','paint-order':'stroke'}:{})},mini);
    });
    Object.values(NODES).forEach(n=>drawNode(mini, n, 22, 4));
    return mini;
  }
  function edgesForCell(cellData){
    // cellData.phases is already the right top-3 data even at the trained corner (see showDataset's grid-click
    // handler below); TRAINED_EDGES is reserved for the tracked lens alone, same rule as edgesForCurrent.
    return lens==='tracked' ? trackedEdgesFor(cellData.key) : edgesFromPhases(cellData.phases);
  }
  // one small curve per grid panel: the selectivity gap (feature mean minus the rest of the interior) over the run,
  // this panel's code solid, the trained code dashed behind it, on one shared axis across every panel.
  const GAP_SERIES=key=>{ const c=COND.curves[key]; return c.featureMean.map((v,i)=>v-c.backgroundMean[i]); };
  const GAP_LO=-0.3, GAP_HI=0.9;
  function sparkline(key){
    const W=640, H=190, x0=6, x1=634, y0=10, y1=140;
    const sp=document.createElementNS(NS,'svg'); sp.setAttribute('viewBox',`0 0 ${W} ${H}`); sp.setAttribute('class','spark');
    const X=it=>x0+it/504*(x1-x0), Y=v=>y1-(Math.max(GAP_LO,Math.min(GAP_HI,v))-GAP_LO)/(GAP_HI-GAP_LO)*(y1-y0);
    PHASES.forEach(ph=>{ const [a,b]=PHASE_SPANS[ph.key]; el('rect',{x:X(a),y:y0,width:X(b)-X(a),height:y1-y0,fill:ph.color,'fill-opacity':0.09},sp); });
    [0,0.4].forEach(v=>el('line',{x1:x0,x2:x1,y1:Y(v),y2:Y(v),stroke:'var(--line)','stroke-width':v===0?3:2},sp));
    const d=vals=>vals.map((v,i)=>`${i?'L':'M'}${X(COND_ITER[i]).toFixed(1)} ${Y(v).toFixed(1)}`).join(' ');
    if(key!=='trained') el('path',{d:d(GAP_SERIES('trained')),fill:'none',stroke:'var(--ink-3)','stroke-width':4,'stroke-dasharray':'12 9','stroke-opacity':0.8},sp);
    el('path',{d:d(GAP_SERIES(key)),fill:'none',stroke:'var(--ink)','stroke-width':6,'stroke-linejoin':'round'},sp);
    const final=GAP_SERIES(key).slice(-1)[0];
    const t=el('text',{x:x1,y:H-8,'text-anchor':'end','font-size':40,fill:'var(--ink-2)','font-family':'IBM Plex Mono, monospace'},sp);
    t.textContent=fmtSigned(final);
    return sp;
  }
  let currentPairKey=null, currentCells=null;
  function decorateCell(cell, cellData, r, c){
    if(cellData.key==='trained'){ const t=document.createElement('span'); t.className='badge left'; t.textContent='trained'; cell.appendChild(t); }
    if(cellData.clipped>0){ const t=document.createElement('span'); t.className='badge right'; t.textContent=`${cellData.clipped} of 40 clipped`; t.title=`${cellData.clipped} of the 40 ring cells had their held value cut to stay inside 0–2 G_pol / G_ref`; cell.appendChild(t); }
  }
  function renderGridThumbnails(){
    if(!currentCells) return;
    gridWrap.querySelectorAll('.gridCell').forEach((cell,idx)=>{
      const r=Math.floor(idx/GRID_SIZE), c=idx%GRID_SIZE;
      while(cell.firstChild) cell.removeChild(cell.firstChild);
      cell.appendChild(miniDiagram(edgesForCell(currentCells[r][c]), 150, currentCells[r][c].key));
      cell.appendChild(sparkline(currentCells[r][c].key));
      decorateCell(cell, currentCells[r][c], r, c);
    });
  }
  function renderGrid(){
    const pairKey=gridPairSelect.value||Object.keys(GRID_DATA)[0]; gridPairSelect.value=pairKey;
    const pair=GRID_DATA[pairKey], [rowOrder,colOrder]=pair.orders;
    currentPairKey=pairKey; currentCells=pair.cells;
    while(gridWrap.firstChild) gridWrap.removeChild(gridWrap.firstChild);
    while(gridRowLabels.firstChild) gridRowLabels.removeChild(gridRowLabels.firstChild);
    while(gridColLabels.firstChild) gridColLabels.removeChild(gridColLabels.firstChild);
    gridWrap.style.gridTemplateColumns=`repeat(${GRID_SIZE}, 1fr)`;
    gridColLabels.style.gridTemplateColumns=`repeat(${GRID_SIZE}, 1fr)`;
    GRID_LEVELS.forEach(lv=>{ const d=document.createElement('div'); d.className='gridAxisLabel'; d.textContent=`order ${colOrder}: ${lv}`; gridColLabels.appendChild(d); });
    gridRowLabels.style.gridTemplateRows=`repeat(${GRID_SIZE}, 1fr)`;
    GRID_LEVELS.forEach(lv=>{ const d=document.createElement('div'); d.className='gridAxisLabel'; d.style.writingMode='vertical-rl'; d.style.transform='rotate(180deg)'; d.textContent=`order ${rowOrder}: ${lv}`; gridRowLabels.appendChild(d); });
    for(let r=0;r<GRID_SIZE;r++) for(let c=0;c<GRID_SIZE;c++){
      const cellData=pair.cells[r][c];
      const cell=document.createElement('div'); cell.className='gridCell';
      cell.appendChild(miniDiagram(edgesForCell(cellData), 150, cellData.key));
      cell.appendChild(sparkline(cellData.key));
      decorateCell(cell, cellData, r, c);
      cell.addEventListener('click',()=>{
        gridWrap.querySelectorAll('.gridCell').forEach(x=>x.classList.remove('current')); cell.classList.add('current');
        showDataset(cellData.key, cellData.phases);   // cellData.phases at the trained cell is already the correct top-3 data
        const gapText = ` (selectivity gap ${fmtSigned(gapOfCurves(COND.curves[cellData.key]))} at iteration 504, stripe overlap ${cellData.overlap.toFixed(2)})`;
        modeExplainer.textContent=`Now showing: order ${rowOrder} ${GRID_LEVELS[r]}, order ${colOrder} ${GRID_LEVELS[c]}${gapText}${clippedText(cellData.clipped)}. ${EXPLAIN.grid}`;
      });
      gridWrap.appendChild(cell);
    }
  }
  gridPairSelect.addEventListener('change',renderGrid);
  const gridDiffOnlyBox=document.getElementById('rlGridDiffOnly');
  gridDiffOnlyBox.addEventListener('change',()=>{ gridDiffOnly=gridDiffOnlyBox.checked; renderGridThumbnails(); });
  const gridShowNetworkBox=document.getElementById('rlGridShowNetwork');
  gridShowNetworkBox.addEventListener('change',()=>{ gridShowNetwork=gridShowNetworkBox.checked; renderGridThumbnails(); });
  const gridVmemBox=document.getElementById('rlGridVmem');
  gridVmemBox.addEventListener('change',()=>{ gridVmem=gridVmemBox.checked; renderGridThumbnails(); });
  const gridShowArrowsBox=document.getElementById('rlGridShowArrows');
  gridShowArrowsBox.addEventListener('change',()=>{ gridShowArrows=gridShowArrowsBox.checked; renderGridThumbnails(); });

  // ---------------- steering lab: move the three orders, see what the nearest simulated codes do ----------------
  // The ring's four region levels are computed exactly from the orders (the clipped cosine basis, as the simulations used). The network is a
  // Gaussian-kernel average, in region-level space, of the top-three edges of every simulated ring code (the page's own, and the sweep): so it
  // reports what nearby simulations did, with an effective count of how many that is. LAB is generated by assembleRelayLoopStripesSteeringData11x11.py.
  (function steeringLab(){
    const cols=LAB.columns, count=LAB.codes, H=LAB.bandwidth, coeff=LAB.trainedCoefficients, NO=coeff.length;
    const sliders=document.getElementById('rlLabSliders'), presetSelect=document.getElementById('rlLabPreset'), readout=document.getElementById('rlLabReadout'),
          warn=document.getElementById('rlLabWarn'), ringSvg=document.getElementById('rlLabRing'), netSvg=document.getElementById('rlLabNet'), legend=document.getElementById('rlLabLegend');
    const inputs=[], outputs=[], signed3=v=>(v>=0?'+':'−')+Math.abs(v).toFixed(3);
    for(let o=0;o<NO;o++){
      const row=document.createElement('div'); row.className='labSlider';
      const label=document.createElement('span'); label.textContent='order '+o;
      const input=document.createElement('input'); input.type='range'; input.step='0.001'; input.value='0';
      input.min=String(Math.max(-0.5,LAB.coefficientLowest[o]-coeff[o])); input.max=String(Math.min(0.5,LAB.coefficientHighest[o]-coeff[o]));
      input.setAttribute('aria-label','offset of order '+o+"'s coefficient from its trained value");
      const out=document.createElement('output'); out.textContent=signed3(0);
      input.addEventListener('input',()=>update());
      row.appendChild(label); row.appendChild(input); row.appendChild(out); sliders.appendChild(row); inputs.push(input); outputs.push(out);
    }
    LAB.presets.forEach((p,i)=>{ const o=document.createElement('option'); o.value=String(i); o.textContent=p.name; presetSelect.appendChild(o); });
    function setOffsets(m){ m.forEach((v,o)=>{ inputs[o].value=String(v); }); update(); }
    presetSelect.addEventListener('change',()=>setOffsets(LAB.presets[+presetSelect.value].offsets));
    document.getElementById('rlLabReset').addEventListener('click',()=>{ presetSelect.value='0'; setOffsets([0,0,0]); });

    function ringOf(offsets){
      const raw=LAB.ringBasis.map(row=>row.reduce((s,b,o)=>s+b*(coeff[o]+offsets[o]),0));
      const sums=[0,0,0,0], counts=[0,0,0,0];
      raw.forEach((v,i)=>{ const c=Math.min(2,Math.max(0,v)); sums[LAB.ringBin[i]]+=c; counts[LAB.ringBin[i]]++; });
      return {levels:sums.map((s,i)=>s/counts[i]), clipped:raw.filter(v=>v<0||v>2).length, coefficients:offsets.map((d,o)=>coeff[o]+d)};
    }
    function estimate(levels){
      let sw=0, sw2=0, push=0, leak=0, formed=0, upper=0, lower=0, overlap=0, gap=0, nearest=-1, nearestD2=1e9;
      const edge=new Float64Array(LAB.edges.length);
      for(let i=0;i<count;i++){
        const l=cols.levels[i]; let d2=0; for(let r=0;r<4;r++){ const d=l[r]-levels[r]; d2+=d*d; }
        if(d2<nearestD2){ nearestD2=d2; nearest=i; }
        const w=Math.exp(-d2/(2*H*H)); if(w<1e-6) continue;
        sw+=w; sw2+=w*w; push+=w*cols.push[i]; leak+=w*cols.leak[i]; overlap+=w*cols.overlap[i]; gap+=w*cols.gap[i];
        if(cols.overlap[i]>=0.9) formed+=w; if(cols.upperDark[i]>=11) upper+=w; if(cols.lowerDark[i]>=11) lower+=w;
        for(const e of cols.edgeIds[i]) edge[e]+=w;
      }
      if(sw<1e-9) return {neff:0, nearest, distance:Math.sqrt(nearestD2), edge:null};
      for(let e=0;e<edge.length;e++) edge[e]/=sw;
      return {neff:sw*sw/sw2, nearest, distance:Math.sqrt(nearestD2), edge, push:push/sw, leak:leak/sw, formed:formed/sw, upper:upper/sw, lower:lower/sw, overlap:overlap/sw, gap:gap/sw};
    }
    const trainedEstimate=estimate(LAB.trainedLevels);

    function drawRing(levels, trained){
      while(ringSvg.firstChild) ringSvg.removeChild(ringSvg.firstChild);
      const x0=34, y0=14, y1=108, Y=v=>y1-(v/2)*(y1-y0), bw=40, gapx=30;
      [0,1,2].forEach(v=>{ el('line',{x1:x0-4,x2:332,y1:Y(v),y2:Y(v),stroke:'var(--line)','stroke-width':v===1?0.6:1},ringSvg);
        const t=el('text',{x:x0-8,y:Y(v)+3.5,'text-anchor':'end','font-size':9.5,fill:'var(--ink-3)','font-family':'IBM Plex Mono, monospace'},ringSvg); t.textContent=String(v); });
      el('line',{x1:x0-4,x2:332,y1:Y(1.439),y2:Y(1.439),stroke:'var(--feature)','stroke-width':1,'stroke-dasharray':'3 3'},ringSvg);
      levels.forEach((v,i)=>{
        const x=x0+i*(bw+gapx);
        el('rect',{x,y:Y(v),width:bw,height:y1-Y(v),fill:'var(--write)','fill-opacity':0.75},ringSvg);
        el('line',{x1:x-4,x2:x+bw+4,y1:Y(trained[i]),y2:Y(trained[i]),stroke:'var(--ink)','stroke-width':2},ringSvg);
        const t=el('text',{x:x+bw/2,y:y1+14,'text-anchor':'middle','font-size':9.5,fill:'var(--ink-2)','font-family':'IBM Plex Mono, monospace'},ringSvg); t.textContent=LAB.regionNames[i];
        const u=el('text',{x:x+bw/2,y:Y(v)-4,'text-anchor':'middle','font-size':9.5,fill:'var(--ink)','font-family':'IBM Plex Mono, monospace'},ringSvg); u.textContent=v.toFixed(3);
      });
      const cap=el('text',{x:332,y:146,'text-anchor':'end','font-size':9.5,fill:'var(--ink-3)'},ringSvg); cap.textContent='G_pol / G_ref · black tick: trained · dashed: 1.439 edge';
    }
    function meter(title, value, reference, hint){
      return `<div class="labMeter"><div class="labMeterHead"><span>${title}</span><b>${Math.round(value*100)}%</b></div>`
        +`<div class="labBar"><i style="width:${(value*100).toFixed(1)}%;background:var(--write)"></i><u style="left:${(reference*100).toFixed(1)}%" title="the trained code's value"></u></div>${hint?`<div class="labNote" style="margin:2px 0 0">${hint}</div>`:''}</div>`;
    }
    function drawNet(est){
      while(netSvg.firstChild) netSvg.removeChild(netSvg.firstChild);
      el('rect',{x:M,y:M,width:11*CM,height:11*CM,fill:'none',stroke:'var(--line)','stroke-width':1},netSvg);
      if(est.edge){
        // for each node pair and phase, the likelier direction, if it is likely enough to draw
        const best=new Map();
        LAB.edges.forEach((e,i)=>{ const k=e[0]+'|'+[e[1],e[2]].sort().join('|'); if(!best.has(k)||est.edge[i]>best.get(k).p) best.set(k,{phase:e[0],from:e[1],to:e[2],p:est.edge[i],id:i}); });
        const shown=[...best.values()].filter(e=>e.p>=0.25).sort((a,b)=>a.p-b.p);
        const trainedGhost=LAB.trainedTopEdges.map(i=>LAB.edges[i]).filter(e=>!shown.some(s=>s.phase===e[0]&&s.from===e[1]&&s.to===e[2]));
        const pathOf=q=>`M ${q.sx.toFixed(1)} ${q.sy.toFixed(1)} Q ${q.mx.toFixed(1)} ${q.my.toFixed(1)} ${q.ex.toFixed(1)} ${q.ey.toFixed(1)}`;
        allEdgesOf(trainedGhost.map(e=>({from:e[1],to:e[2],phase:e[0],bow:laneBow(e[1],e[2],e[0])}))).forEach(e=>{
          el('path',{d:pathOf(computePath(e)),fill:'none',stroke:'var(--ink-3)','stroke-width':3,'stroke-linecap':'round','stroke-dasharray':'2 9',opacity:0.6},netSvg);
        });
        allEdgesOf(shown.map(e=>({from:e.from,to:e.to,phase:e.phase,p:e.p,bow:laneBow(e.from,e.to,e.phase)}))).forEach(e=>{
          const q=computePath(e), w=2+7*e.p, opacity=0.3+0.7*Math.min(1,(e.p-0.25)/0.6), colour=`var(--${e.phase})`;
          el('path',{d:pathOf(q),fill:'none',stroke:colour,'stroke-width':w.toFixed(2),'stroke-linecap':'round',opacity,'data-phase':e.phase,'data-p':e.p.toFixed(2)},netSvg);
          const tx=q.ex-q.mx, ty=q.ey-q.my, tl=Math.hypot(tx,ty)||1, ux=tx/tl, uy=ty/tl, L=14+1.0*w, Hh=L*0.55;
          el('polygon',{points:`${q.ex+ux*4},${q.ey+uy*4} ${q.ex-ux*L-uy*Hh},${q.ey-uy*L+ux*Hh} ${q.ex-ux*L+uy*Hh},${q.ey-uy*L-ux*Hh}`,fill:colour,opacity},netSvg);
        });
      }
      Object.entries(NODES).forEach(([k,n])=>{
        drawNode(netSvg, n, 16, 2.6);
        n.lines.forEach((word,i)=>{ const t=el('text',{x:n.x,y:n.y-23-(n.lines.length-1-i)*13,'text-anchor':'middle','font-size':12,'font-family':"'IBM Plex Mono',monospace",fill:'var(--ink-2)',stroke:'var(--surface)','stroke-width':3,'paint-order':'stroke'},netSvg); t.textContent=word; });
      });
    }
    function update(){
      const m=inputs.map(i=>+i.value); m.forEach((v,o)=>{ outputs[o].textContent=signed3(v); });
      const ring=ringOf(m), est=estimate(ring.levels);
      drawRing(ring.levels, LAB.trainedLevels);
      warn.textContent = ring.clipped ? `${ring.clipped} of the 40 ring cells would leave the legal range 0–2 and are clipped, as in the simulations.` : '';
      drawNet(est);
      const reliability = est.neff>=8 ? 'well covered by simulated codes' : est.neff>=3 ? 'thinly covered: read with caution' : 'outside the explored region: a guess';
      const near=est.nearest, nearKey=cols.key[near], nearCoefficients=cols.coefficients[near].map(v=>v.toFixed(3)).join(', ');
      const coefficientLine=`coefficients a0 ${ring.coefficients[0].toFixed(3)}, a1 ${ring.coefficients[1].toFixed(3)}, a2 ${ring.coefficients[2].toFixed(3)}`;
      readout.innerHTML = est.edge ? (
          `<p class="labNote" style="margin-top:0">${coefficientLine}</p>`
        + meter('Stripe formed at iteration 504 (overlap ≥ 0.9)', est.formed, trainedEstimate.formed, `the share of the nearby simulated codes that form it (their mean overlap is ${est.overlap.toFixed(2)}). The window the stripe forms in is far narrower than the neighbourhood averaged over, so a setting that does form it can read low here: look at the nearest simulated code below`)
        + meter('Upper half of the stripe dark (11 or more of 12)', est.upper, trainedEstimate.upper, '')
        + meter('Lower half of the stripe dark (11 or more of 12)', est.lower, trainedEstimate.lower, '')
        + meter('Ring pushes into the stripe in the clear phase', est.push, trainedEstimate.push, 'clear: ring top → stripe upper or ring bottom → stripe lower is among the three biggest transfers')
        + meter('Stripe leaks into its flank in the clear phase', est.leak, trainedEstimate.leak, 'clear: stripe upper → left flank upper or stripe lower → left flank lower is among the three biggest transfers')
        + `<p class="labNote">Mean selectivity gap of the nearby codes ${fmtSigned(est.gap)}. Estimated from ${est.neff.toFixed(1)} effective simulated codes within about ${H.toFixed(2)} G_pol / G_ref of this setting — ${reliability}. Nearest simulated code: ${nearKey} at ${est.distance.toFixed(3)} (coefficients ${nearCoefficients}; stripe overlap ${cols.overlap[near].toFixed(2)}, ${cols.upperDark[near]} of 12 upper and ${cols.lowerDark[near]} of 12 lower stripe cells dark).</p>`
      ) : `<p class="labNote">${coefficientLine}</p><p class="labNote">No simulated code lies near this setting (nearest: ${nearKey} at ${est.distance.toFixed(3)}).</p>`;
      legend.innerHTML = 'Solid lines: edges that at least a quarter of the nearby simulated codes carry among the three biggest transfers of a phase (thicker and darker = more of them); colours are the phases. Dotted gray: edges the trained code carries that these do not. The ring bars are exact; the network is an average of simulations, not a new simulation.';
    }
    // ---- the story, from the numbers the assembler wrote
    const S=LAB.story, pct=x=>Math.round(100*x)+'%';
    document.getElementById('rlLabStandfirst').innerHTML = `Across ${count} simulated ring codes (${LAB.sources.page} on this page, ${LAB.sources.sweep} in a sweep that covers the whole space of orders and crowds in on the stripe’s window), `
      +`<strong>${S.formed}</strong> end with the stripe at iteration 504 (overlap 0.9 or more). Of those, ${S.formedInWindow} have the ring’s level at both the top and the bottom inside ${S.window[0]}–${S.window[1]}; the window holds ${S.inWindow} codes in all. `
      +`The ring levels that make the stripe span ${S.formedLevels.top?`top ${S.formedLevels.top[0]}–${S.formedLevels.top[1]}, bottom ${S.formedLevels.bottom[0]}–${S.formedLevels.bottom[1]}, sides ${S.formedLevels.side[0]}–${S.formedLevels.side[1]}`:'(none)'}. `
      +`Move any order and watch the ring levels first: the network changes smoothly with them, and the stripe only appears where the top and bottom levels are in the window.`;
    document.getElementById('rlLabStory').innerHTML =
      `<p><strong>The push.</strong> In the clear phase the ring’s top pushes into the upper stripe and its bottom into the lower stripe, both the biggest transfers of the phase. The simulated codes that carry this push in their top three form the stripe much more often than those that do not (see the first meters above as you move the sliders).</p>`
      +`<p><strong>One end at a time.</strong> Of the ${S.codes} codes, ${S.bothHalves} darken both halves of the stripe (11 or more of 12 cells), ${S.upperFormedOnly} only the upper half and ${S.lowerFormedOnly} only the lower: the two ends are written separately, as the confirmation of the ends found.</p>`
      +`<p class="labNote">How far to trust it: a kernel average of simulations, checked by holding out whole blocks of the space. Mean held-out AUC over the edges is ${LAB.skill.meanEdgeAuc.toFixed(2)}; for whether the stripe forms ${LAB.skill.formed.toFixed(2)} (0.5 is chance, 1 is perfect).</p>`;
    document.getElementById('rlLabConfirmation').innerHTML = '<strong>No confirmatory test.</strong> Nothing in this lab was registered; it describes the simulated codes and treats any one edge as a lead, not a finding.';
    update();
  })();


  // ---------------- reading the loop: the trained code's own numbers, written out ----------------
  (function reading(){
    const T=TRAINED_TOP3_PHASES, name=k=>FULL_NAME[k], edge=e=>`${name(e.from)} → ${name(e.to)} (${e.value.toFixed(3)})`;
    const list=p=>(T[p]||[]).map(edge).join('; ');
    const flood=(T.flood||[]), clear=(T.clear||[]);
    const ratio=flood.length&&clear.length ? clear[0].value/flood[0].value : null;
    document.getElementById('rlReading').innerHTML =
      `<p><strong>Flood</strong> (it. 0–301, the clamp writing the ring): the three biggest transfers are ${list('flood')}. The ring’s top and bottom push straight into the two ends of the stripe, and about half as hard into the flank corners beside them; by the end of the hold all 27 stripe cells are dark.</p>`
      +`<p><strong>Clear</strong> (301–504, the release to the readout): the three biggest are ${list('clear')}. The same two pushes carry on${ratio?`, about ${Math.round(ratio)} times as strong as in the flood`:''}, and a small drain begins from each half of the stripe into the flank beside it. The flanks fall through the bottom of their switching window and relight; what is left at 504 is the stripe.</p>`
      +`<p><strong>No write phase.</strong> The stripe code is read at iteration 504, before the interior’s conductance has turned (its trough is at 1130), so this loop stops where the face’s loop begins to reverse. It is a short loop in the sense that matters here: two pushes in, a leak out, nothing that comes back round.</p>`
      +`<p class="labNote">Everything above is the trained code read at iteration 504. A different ring code is read at the same moment, whatever its own best moment is; for the slider and the grid that is what makes the panels comparable.</p>`;
  })();


  // ---------------- the order -> edge map and the locality table (analyzeRelayLoopStripesOrderEdgeMap11x11.py) ----------------
  (function orderEdgeMap(){
    const M2=D.orderEdgeMap; if(!M2) return;
    ['rlMapTitle','rlMapText','rlMapFigure','rlLocalFigure'].forEach(id=>{ document.getElementById(id).hidden=false; });
    const rows=M2.orderMap, svgM=document.getElementById('rlOrderEdgeMap');
    const regionNames=M2.regionLoadingsOfOrders.regions, orderNames=Array.from({length:M2.orders},(_,o)=>'order '+o);
    const nice=s=>s.replace(/ring(Top|Bottom|Left|Right)/g,(m,a)=>'ring '+a.toLowerCase()).replace(/stripe(Upper|Lower)/g,(m,a)=>'stripe '+a.toLowerCase()).replace(/flankLeft(Upper|Lower)/g,(m,a)=>'flank '+a.toLowerCase()).replace(/->/g,'→');
    const rowH=22, top=62, left=330, colW=64, gapX=26, W=900, H=top+rows.length*rowH+20;
    svgM.setAttribute('viewBox',`0 0 ${W} ${H}`);
    const limit=Math.max(0.01,...rows.flatMap(r=>[...r.regionLogitPerSd.map(Math.abs),...r.orderLogitPerTenthCoefficient.map(Math.abs)]));
    const blocks=[{title:'by ring region (logit per +1 sd)',key:'regionLogitPerSd',stab:'regionSignStability',labels:regionNames,x:left},
                  {title:'by order (logit per +0.1 of its coefficient)',key:'orderLogitPerTenthCoefficient',stab:'orderSignStability',labels:orderNames,x:left+regionNames.length*colW+gapX}];
    blocks.forEach(b=>{
      tx(b.title,{x:b.x,y:16,'font-size':11,fill:'var(--ink-2)'},svgM);
      tx('? = sign not stable in 90% of bootstraps',{x:b.x,y:30,'font-size':9.5},svgM);
      b.labels.forEach((l,j)=>tx(l,{x:b.x+j*colW+colW/2,y:top-8,'text-anchor':'middle','font-size':10.5,fill:'var(--ink-2)'},svgM));
      rows.forEach((r,i)=>b.labels.forEach((l,j)=>{
        const v=r[b.key][j], sure=r[b.stab][j]>=0.9, rect=el('rect',{x:b.x+j*colW,y:top+i*rowH,width:colW-1.5,height:rowH-1.5,fill:v>=0?'var(--ochre)':'var(--teal)','fill-opacity':(0.06+0.86*Math.abs(v)/limit).toFixed(3)},svgM);
        tx((v>=0?'+':'−')+Math.abs(v).toFixed(2)+(sure?'':'?'),{x:b.x+j*colW+colW/2-0.7,y:top+i*rowH+rowH/2+3.5,'text-anchor':'middle','font-size':10,'font-family':MONO,fill:'var(--ink)'},svgM);
        hook(rect,()=>`${nice(r.edge)}<br>${l}: ${v>=0?'+':'−'}${Math.abs(v).toFixed(3)} logit, sign stable in ${Math.round(r[b.stab][j]*100)}% of bootstraps`);
      }));
    });
    rows.forEach((r,i)=>tx(`${nice(r.edge)}  (AUC ${r.blockedAuc.toFixed(2)})`,{x:left-8,y:top+i*rowH+rowH/2+3.5,'text-anchor':'end','font-size':10.5,fill:'var(--ink-2)'},svgM));
    const learn=M2.learnableEdges, total=M2.edgeScores.length, stripes=M2.outcomes.stripesInSweep;
    document.getElementById('rlMapText').textContent=`For each edge that is among a phase’s three biggest transfers in between 8% and 92% of the ${M2.sweepCodes} sweep codes, a regression asks how each ring region’s level changes the odds that the edge is in the top three. ${learn} of the ${total} such edges are learnable (held-out AUC at least 0.70 and 0.05 above a shuffled-label null); the map is for those. The order columns compose the region map with how each order loads on the regions, per +0.1 of its coefficient. Of the ${stripes.codes} sweep codes ${stripes.atLeast0_9} make the stripe (overlap 0.9 or more at 504).`;
    document.getElementById('rlMapCaption').textContent=`Orange: the edge becomes more likely to be in the top three as the region or order goes up; teal: less likely. Blocked AUC is the held-out score when whole blocks of coefficient space are left out. Exploratory: nothing here was registered, and with this many edges and looks, treat a single cell as a lead, not a finding.`;
    // the locality table
    const t=document.getElementById('rlLocalTable'), pct=x=>Math.round(100*x)+'%';
    t.innerHTML='<tr><th>distance from the stripe code (coefficient space)</th><th>codes</th><th>mean share of the trained top-three set kept</th><th>mean selectivity gap</th><th>stripe formed (overlap ≥ 0.9)</th></tr>'
      +M2.local.map(l=>`<tr><td class="mono">${l.radius}</td><td class="mono">${l.codes}</td><td class="mono">${pct(l.meanTopThreeRetention)}</td><td class="mono">${l.meanGap.toFixed(2)}</td><td class="mono">${l.stripeAtLeast0_9} of ${l.codes}</td></tr>`).join('');
    document.getElementById('rlLocalCaption').textContent=`The share is Jaccard similarity of the code’s set of top-three edges (both phases) with the trained code’s. If the net changed smoothly with the ring code, the share would fall off steadily with distance; the last column is how the outcome itself behaves over the same distances. R² of a held-out regression of the stripe’s overlap on the four region levels: ${M2.outcomes.stripeOverlap.blockedRSquared.toFixed(2)}; of the gap: ${M2.outcomes.gap.blockedRSquared.toFixed(2)}.`;
  })();

  variantSelect.value='trained'; sliderOrderSelect.value='0'; gridPairSelect.value='0_1'; resetSlider();
  setMode('single');
})();
